### ISSUE TITLE
CVD - Export Zip Altium Package

### ISSUE THREAD

**Issue by esc-works** [RespiraWorks/SystemDesign#122]
Edwin told me how to export this and I will get it done

**Comment by inceptionev** [comment]
Design Files: https://drive.google.com/file/d/1bujMaEhlp7HlqBhJcG2bO4sFTghJyMfL/view?usp=sharing

Manufacturing Files: https://drive.google.com/file/d/13IxR1hi02mj8zuQjK6Vfy6ekf4aIQ03Q/view?usp=sharing

**Comment by esc-works** [comment]
Woo!! first thing done. FYI I renamed these files and moved them to the "ready for submission" folder

**Comment by inceptionev** [comment]
Actually, probably better to use github links since we are open-source:

Design: https://github.com/RespiraWorks/pcbreathe/blob/master/NIGHTLY/20200424v2-RELEASE-CANDIDATE-2/20200424v2-RespiraWorks-Ventilator-Rev1.0-RC2-PKG-DESIGN.zip

Manufacturing: https://github.com/RespiraWorks/pcbreathe/blob/master/NIGHTLY/20200424v2-RELEASE-CANDIDATE-2/20200424v2-RespiraWorks-Ventilator-Rev1.0-RC2-PKG-TURNKEY.zip
